# fly.toml app configuration file generated for ralph-api-frosty-silence-3545 on 2026-06-27T17:59:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ralph-api-frosty-silence-3545'
primary_region = 'lhr'

[build]
  dockerfile = 'apps/api/Dockerfile'
  build-target = 'runner'

[env]
  NODE_ENV = 'production'
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = 'tcp'
  internal_port = 4000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
